Adding init script
autolab/docker pull request #1
Opened 2020-09-24 03:44 UTC by Huahan98

Added a setup.sh which should be run before `docker-compose up` for the first time (consider running `docker-compose build --no-cache` to clear existing build cache). 

**How it is tested:**
After running `sh setup.sh && docker-compose up`, I sshed into the docker container (`docker exec -it docker_autolab_1 /bin/bash`) and examined config/initializers/devise.rb. `config.secret_key` had been changed to a random string as expected.

2020-09-24 20:58 UTC, fanpu commented on setup.sh
> +sed -i "" "s/<YOUR-SECRET-KEY>/`LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 128`/g" Autolab/docker/devise.rb
Is the first "" supposed to be there? On my Linux system if I run it as it is I get:

`sed: can't read s/<YOUR-SECRET-KEY>/9VNBfk8sM5jreVSx7VxrIQJHMS4LLJ8n2ph3360CgIiL6LfRliIQSD188W0fJbk6lvj6GDvh0IQKz0BH4FnZc1bcQrsBikKF9RrOoFWWPu32a1SJUbcCDx8aL9GHoEjV/g: No such file or directory`

which is because it's taking the first string as the substitution string and the second string as the filename. I know that on Mac you are required to specify a backup file extension, which is what this might be referring to. In this case, 

`sed -i"" "s/<YOUR-SECRET-KEY>/`LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 128`/g" Autolab/docker/devise.rb`

would work (no spaces after the -i flag), which I tested on my system. Hope this helps!

2020-09-24 20:59 UTC, fanpu requested changes
See comment

2020-09-24 22:43 UTC, Huahan98 commented on setup.sh
> +sed -i "" "s/<YOUR-SECRET-KEY>/`LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 128`/g" Autolab/docker/devise.rb
Thanks for the suggestion! However after I removed the spaces, I got the following error on my Mac system:
`sed: 1: "Autolab/docker/devise.rb": invalid command code A`. 

But since we are assuming to run on a Linux system and running `sed -i""` works on Linux, I have updated the code according to your comment.

2020-09-27 00:00 UTC, fanpu approved these changes

2020-09-29 18:00 UTC, merged