Jenkins CD
autolab/docker pull request #41
Opened 2021-10-28 21:54 UTC by Huahan98

Continuous Deployment for Autolab demo site using Jenkins. 

Jenkins dashboard: http://jenkins.autolabproject.com:8090/job/autolab-demo-test/

To test, please go to nightly.autolabproject.com and log in using the credentials (this initial user is set up by the pipeline):

_email: admin@demo.bar
password: adminfoobar_

2021-11-18 22:09 UTC, fanpu commented on docker-compose.yml
>  version: "3.3"
I know you changed the container_name here to get around the original issue of not conflicting with existing container names, but this problem now becomes circular if we actually modify it. I think there are at least two approaches here we can take to resolve this:

1. Have another docker-compose.yml for CI, with modified names for containers
2. Don't have conflicting deployments on our CI machine

I think we can just go with 2, since our CI deployment can be our demo deployment as we don't have strict uptime requirements

2021-11-18 22:13 UTC, fanpu commented
Some nits but otherwise looks good! The main thing is just with fixing the issues on container names

2021-11-18 22:13 UTC, fanpu requested changes

2021-11-18 22:13 UTC, fanpu commented on Makefile
>  db-migrate:
Nit, but recommend adding a comment near the top of file that ci-prefixed commands are meant to be executed by our CI pipeline and users should just ignore them. I think users do inspect Makefiles to see what's available to them, so this is just to avoid any confusion from them.

2021-11-18 22:13 UTC, fanpu commented on ssl/init-letsencrypt-ci.sh.template
> +# Run this from the root of the Autolab docker installation directory (not from the ssl subdirectory)
update this comment to mention this is meant for CI, if you're looking at this as a user you should be looking at the other file (init-letsencrypt.sh.template)

2021-12-02 23:15 UTC, fanpu approved these changes
LGTM!

2021-12-02 23:36 UTC, Huahan98 commented on Makefile
>  db-migrate:
thanks! I will address this

2021-12-06 03:44 UTC, merged